### ISSUE TITLE
ISE /accounts/login - kerberos is not set

### ISSUE THREAD

**Issue by Pajinek** [SatelliteQE/GreenTea#4]
Show page with information about setup kerberos when kerberos is not set.

Build passed, starting it passed, I get to the main dashboard but on
http://localhost/accounts/login I get

```
AttributeError at /accounts/login

'NoneType' object has no attribute 'split'

Request Method: 	GET
Request URL: 	http://ibm-dx360m4-01.rhts.eng.bos.redhat.com/accounts/login
Django Version: 	1.5.12
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute 'split'

Exception Location: 	/data/GreenTea/apps/kerberos/views.py in dispatch, line 15
Python Executable: 	/data/GreenTea/env/bin/python
Python Version: 	2.7.10
Python Path: 	

['/data/GreenTea/env/lib/python2.7/site-packages/git/ext/gitdb',
 '/data/GreenTea',
 '/data/GreenTea/env/lib64/python27.zip',
 '/data/GreenTea/env/lib64/python2.7',
 '/data/GreenTea/env/lib64/python2.7/plat-linux2',
 '/data/GreenTea/env/lib64/python2.7/lib-tk',
 '/data/GreenTea/env/lib64/python2.7/lib-old',
 '/data/GreenTea/env/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7',
 '/usr/lib/python2.7',
 '/data/GreenTea/env/lib/python2.7/site-packages',
 '/data/GreenTea/env/lib/python2.7/site-packages/gitdb/ext/smmap']
```

and

```
Traceback (most recent call last):
  File "/data/GreenTea/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/data/GreenTea/env/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/GreenTea/apps/kerberos/views.py", line 15, in dispatch
    username, real = self.remote_user.split("@")
AttributeError: 'NoneType' object has no attribute 'split'
```

on container's output.

**Comment by Pajinek** [comment]
Fixed in patch https://github.com/SatelliteQE/GreenTea/commit/6c913757db82028814759c7dfb0fa7a7e31f852b
