### ISSUE TITLE
lots of errors in info.log

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/GreenTea#77]
[root@tttt ~]# grep ^Traceback /data/greentea/log/info.log | wc -l
1080
[root@tttt ~]# grep ^ProtocolError /data/greentea/log/info.log | wc -l
1080
[root@tttt ~]# grep "codec can't decode bytes in position" /data/greentea/log/info.log | wc -l
270

PUT http://0.0.0.0:9200/testout.log/log/576513 [status:N/A request:12.865s]
Traceback (most recent call last):
  File "/data/greentea/web/env/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/data/greentea/web/env/lib/python2.7/site-packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/data/greentea/web/env/lib/python2.7/site-packages/urllib3/util/retry.py", line 232, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data/greentea/web/env/lib/python2.7/site-packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/data/greentea/web/env/lib/python2.7/site-packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 979, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 811, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
indexing /.../TESTOUT.log: 'utf8' codec can't decode byte 0xe2 in position 37930: invalid continuation byte

Is that OK? Was investigating this because of higher load on the machine, not sure if that is related.

**Comment by Pajinek** [comment]
I found a lot of  traceback in elastic search. It looks that problem is with large logs.

```
[2016-05-23 09:45:02,247][WARN ][http.netty               ] [Lament] Caught exception while handling client http traffic, closing connection [id: 0xd726035b, /172.17.0.1:52035 => /172.17.0.2:9200]
org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
```
